### ISSUE TITLE
Possible incompatibility with iPhone 11 Pro or iOS 13

### ISSUE THREAD

**Issue by PhilipTeitel** [rob-miller/rTracker#2] opened 2019-10-12 14:42 UTC
Since getting the new iPhone, I’ve had 2 instances where the app posted a message about recovering data. Then when the dialog went away, there was no data.  On the first one, I had the data saved from my recent migration.  I still have that data, but it’s as if the last week didn’t happen.  

I don’t know if this code is still maintained, but if so, thanks in advance.

**Comment by rob-miller** [comment] 2019-10-15 11:57
I'm sorry to read that you've lost data.  I have not seen this problem on my new Xs max, also on iOS 13, and obviously it should not happen at all.  I would not think there would be any difference with the iPhone 11 on the software side.

The recovery code is activated when rTracker starts up (rather than just becomes active) and there is a discrepancy between IDs stored in the top level list of trackers and the individual tracker database files.  If it finds a tracker file without a corresponding entry in the top level list (an orphan), it should prepend the string 'recovered:' to the tracker name and make it available in the tracker list.  

The only situation where it deletes the orphan tracker file is if it tries to load the file but the tracker name is empty; more could be done here, such as naming it to something like 'no name', but the presumption is that it really is corrupt or an aborted attempt to create a new tracker.  As this code is (should be) triggered infrequently, something may have changed in the iOS handling of renaming the tracker file in the last few years of iOS versions.

I intend to update rTracker to add some features and the correct display sizes for the newer model iPhones, but this is not my main priority right now so I am not sure how soon I will get to it.  I will make this section of code more bulletproof at that time.

I'm curious about how you migrated data to the new phone (by exporting and reloading the tracker files, emailing, or just from the full phone backup)?  Also, was there any obvious change in language or character set when moving to the new phone?

For your specific case now, I would suggest exporting and backing up all of your tracker files, then delete and re-import the one that has had the problem.  E-mailing to yourself might be best as the .rtrk file should be easiest to re-import.  Then do some experimentation - add some data, followed by killing rTracker (flick out of the task list) and reloading it to try to trigger the recovery code.  

If you can identify a situation to reproduce the problem and your data is not too private, I would be interested in having a play if you'd like to send your tracker file (email in my github profile).  Otherwise, your goal is to get the top-level database consistent with the tracker files so the recovery routine does not trigger.  If all else fails, emailing the trackers to yourself, deleting & reinstalling rTracker, and restoring the trackers from the emails is probably the most robust solution.

**Comment by andrewmwhite** [comment] 2019-12-10 22:48
I hit the same issue after upgrading to iOS 13 on an iPhone X. I didn’t port the data in any way other than updating iOS. 

All my trackers disappeared. I tried restoring from an old set of CSVs but the issue reoccurred shortly thereafter so I haven’t used the app in the last few weeks. :-(

I don’t think I can email myself the rtrk files since there’s no data displaying in the app right now. I can try restoring again from CSV.

**Comment by rob-miller** [comment] 2019-12-11 09:12
OK, in my hands on the Xs Max the graphs aren't working correctly since the update to iOS 13 but no other problems.  I hope to be working on an update in the next few weeks and will see what I can do to address this.  

I'm interested to know:
- is your phone is set to back up to computer or iCloud?  if iCloud is it full? Is the phone storage approaching full?
- when the issue reoccurred 'shortly thereafter' does that mean next 2-3 times you used it, or more like days/weeks later?  
- does 'no data' mean all the trackers are still there, but no data is accessible by swiping back, 'go to date' or viewing the graph?  Or is everything gone including the top level list of trackers and/or the individual trackers ?

**Comment by andrewmwhite** [comment] 2019-12-11 17:05
- I back up to computer occasionally, not iCloud. Phone storage is at 125gb/256gb.
- Almost immediately, maybe even the next time I used it. Can’t remember exactly. 
- Everything’s gone including the top-level tracker list and all the individual trackers. It’s just a blank page when I open the app.

**Comment by rob-miller** [comment] 2020-01-21 19:05
OK, update submitted to App Store and merged into master branch.  
The issues, both the graph problems on the Xs Max and the corrupted databases on the iPhone 11 were due to race conditions presumably exposed by the faster processors on these devices.  
Hopefully these are fixed now.

**Closed as completed by rob-miller** 2020-01-21 19:05 UTC
